using Newtonsoft.Json;

namespace RacemenuPresetConverter.Models
{
    public class BBBMorphs
    {
        [JsonProperty("7B Lower")]
        public MorphValue SevenBLower { get; set; }

        [JsonProperty("7B Upper")]
        public MorphValue SevenBUpper { get; set; }

        [JsonProperty("7BLeg_v2")]
        public MorphValue SevenBLeg_v2 { get; set; }

        public MorphValue AnalLoose_v2 { get; set; }
        public MorphValue AnalPosition_v2 { get; set; }
        public MorphValue AnalTexPosRe_v2 { get; set; }
        public MorphValue AnalTexPos_v2 { get; set; }
        public MorphValue AnkleSize { get; set; }
        public MorphValue AppleCheeks { get; set; }
        public MorphValue AreolaPull_v2 { get; set; }
        public MorphValue AreolaSize { get; set; }
        public MorphValue ArmpitShape_v2 { get; set; }
        public MorphValue Arms { get; set; }
        public MorphValue Back { get; set; }
        public MorphValue BackArch { get; set; }
        public MorphValue BackValley_v2 { get; set; }
        public MorphValue BackWing_v2 { get; set; }
        public MorphValue Belly { get; set; }
        public MorphValue BellyFrontDownFat_v2 { get; set; }
        public MorphValue BellyFrontUpFat_v2 { get; set; }
        public MorphValue BellySideDownFat_v2 { get; set; }
        public MorphValue BellySideUpFat_v2 { get; set; }
        public MorphValue BellyUnder_v2 { get; set; }
        public MorphValue BigBelly { get; set; }
        public MorphValue BigButt { get; set; }
        public MorphValue BigTorso { get; set; }
        public MorphValue BreastCenter { get; set; }
        public MorphValue BreastCenterBig { get; set; }
        public MorphValue BreastCleavage { get; set; }
        public MorphValue BreastFlatness { get; set; }
        public MorphValue BreastFlatness2 { get; set; }
        public MorphValue BreastGravity2 { get; set; }
        public MorphValue BreastHeight { get; set; }
        public MorphValue BreastPerkiness { get; set; }
        public MorphValue BreastSideShape { get; set; }
        public MorphValue BreastTopSlope { get; set; }
        public MorphValue BreastUnderDepth { get; set; }
        public MorphValue BreastWidth { get; set; }
        public MorphValue Breasts { get; set; }
        public MorphValue BreastsConverage_v2 { get; set; }
        public MorphValue BreastsFantasy { get; set; }
        public MorphValue BreastsGone { get; set; }
        public MorphValue BreastsNewSH { get; set; }
        public MorphValue BreastsNewSHSymmetry { get; set; }
        public MorphValue BreastsPressed_v2 { get; set; }
        public MorphValue BreastsSmall { get; set; }
        public MorphValue BreastsSmall2 { get; set; }
        public MorphValue BreastsTogether { get; set; }
        public MorphValue Butt { get; set; }
        public MorphValue ButtClassic { get; set; }
        public MorphValue ButtCrack { get; set; }
        public MorphValue ButtDimples { get; set; }
        public MorphValue ButtNarrow_v2 { get; set; }
        public MorphValue ButtPressed_v2 { get; set; }
        public MorphValue ButtSaggy_v2 { get; set; }
        public MorphValue ButtShape2 { get; set; }
        public MorphValue ButtSmall { get; set; }
        public MorphValue ButtUnderFold { get; set; }
        public MorphValue CBPC { get; set; }
        public MorphValue CalfFBThicc_v2 { get; set; }
        public MorphValue CalfSize { get; set; }
        public MorphValue CalfSmooth { get; set; }
        public MorphValue ChestDepth { get; set; }
        public MorphValue ChestWidth { get; set; }
        public MorphValue ChubbyArms { get; set; }
        public MorphValue ChubbyButt { get; set; }
        public MorphValue ChubbyLegs { get; set; }
        public MorphValue ChubbyWaist { get; set; }
        public MorphValue Clavicle_v2 { get; set; }
        public MorphValue Clit { get; set; }
        public MorphValue ClitSwell_v2 { get; set; }
        public MorphValue CrotchBack { get; set; }
        public MorphValue CrotchGap { get; set; }
        public MorphValue Cutepuffyness { get; set; }
        public MorphValue DoubleMelon { get; set; }
        public MorphValue FeetFeminine { get; set; }
        public MorphValue ForearmSize { get; set; }
        public MorphValue Groin { get; set; }
        public MorphValue HipBone { get; set; }
        public MorphValue HipCarved { get; set; }
        public MorphValue HipForward { get; set; }
        public MorphValue HipNarrow_v2 { get; set; }
        public MorphValue HipUpperWidth { get; set; }
        public MorphValue Hips { get; set; }
        public MorphValue Innieoutie { get; set; }
        public MorphValue KneeHeight { get; set; }
        public MorphValue KneeShape { get; set; }
        public MorphValue KneeTogether_v2 { get; set; }
        public MorphValue LabiaBulgogi_v2 { get; set; }
        public MorphValue LabiaCrumpled_v2 { get; set; }
        public MorphValue LabiaMorePuffyness_v2 { get; set; }
        public MorphValue LabiaNeat_v2 { get; set; }
        public MorphValue LabiaTightUp { get; set; }
        public MorphValue Labiaprotrude { get; set; }
        public MorphValue Labiaprotrude2 { get; set; }
        public MorphValue Labiaprotrudeback { get; set; }
        public MorphValue Labiapuffyness { get; set; }
        public MorphValue Labiaspread { get; set; }
        public MorphValue LegShapeClassic { get; set; }
        public MorphValue LegSpread_v2 { get; set; }
        public MorphValue LegsThin { get; set; }
        public MorphValue MuscleAbs { get; set; }
        public MorphValue MuscleArms { get; set; }
        public MorphValue MuscleBack_v2 { get; set; }
        public MorphValue MuscleButt { get; set; }
        public MorphValue MuscleLegs { get; set; }
        public MorphValue MuscleMoreAbs_v2 { get; set; }
        public MorphValue MuscleMoreArms_v2 { get; set; }
        public MorphValue MuscleMoreLegs_v2 { get; set; }
        public MorphValue MusclePecs { get; set; }
        public MorphValue NavelEven { get; set; }
        public MorphValue NipBGone { get; set; }
        public MorphValue NippleBump_v2 { get; set; }
        public MorphValue NippleCrease_v2 { get; set; }
        public MorphValue NippleCrumpled_v2 { get; set; }
        public MorphValue NippleDip { get; set; }
        public MorphValue NippleDistance { get; set; }
        public MorphValue NippleDown { get; set; }
        public MorphValue NippleInvert_v2 { get; set; }
        public MorphValue NippleLength { get; set; }
        public MorphValue NippleManga { get; set; }
        public MorphValue NipplePerkManga { get; set; }
        public MorphValue NipplePerkiness { get; set; }
        public MorphValue NipplePuffy_v2 { get; set; }
        public MorphValue NippleShy_v2 { get; set; }
        public MorphValue NippleSize { get; set; }
        public MorphValue NippleSquash1_v2 { get; set; }
        public MorphValue NippleSquash2_v2 { get; set; }
        public MorphValue NippleThicc_v2 { get; set; }
        public MorphValue NippleTip { get; set; }
        public MorphValue NippleTipManga { get; set; }
        public MorphValue NippleTube_v2 { get; set; }
        public MorphValue NippleUp { get; set; }
        public MorphValue OldBaseShape { get; set; }
        public MorphValue PregnancyBelly { get; set; }
        public MorphValue PushUp { get; set; }
        public MorphValue RibsMore_v2 { get; set; }
        public MorphValue RibsProminance { get; set; }
        public MorphValue RoundAss { get; set; }
        public MorphValue ShoulderSmooth { get; set; }
        public MorphValue ShoulderTweak { get; set; }
        public MorphValue ShoulderWidth { get; set; }
        public MorphValue SlimThighs { get; set; }
        public MorphValue SternumDepth { get; set; }
        public MorphValue SternumHeight { get; set; }
        public MorphValue ThighFBThicc_v2 { get; set; }
        public MorphValue ThighInsideThicc_v2 { get; set; }
        public MorphValue ThighOutsideThicc_v2 { get; set; }
        public MorphValue Thighs { get; set; }
        public MorphValue TummyTuck { get; set; }
        public MorphValue UNPHip_v2 { get; set; }
        public MorphValue VaginaHole { get; set; }
        public MorphValue Vaginasize { get; set; }
        public MorphValue VanillaSSEHi { get; set; }
        public MorphValue VanillaSSELo { get; set; }
        public MorphValue Waist { get; set; }
        public MorphValue WaistHeight { get; set; }
        public MorphValue WideWaistLine { get; set; }
        public MorphValue WristSize { get; set; }
    }
}
